name: MCTrackerVote
version: '${project.version}'
main: ir.mctracker.mctrackervote.MCTrackerVote
api-version: 1.13
authors: [ Alijk, Cipher ]
description: https://mctracker.ir/ vote handling plugin
website: https://mctracker.ir/
